export const environment = {
  production: true,
  protocol: 'http://',
  access: '/access',
  amqp: '/amqp',
  moradorUrl: '/morador',
  residenciaUrl: '/residencia',
  filtro: '/filtro',
  token: '/token',
  alterar: '/amqp/alterar',
  novo: '/amqp/novo',
  nova: '/amqp/nova',
  processo: '/amqp/processo',
  perfil: '/perfil',
  modulo: '/modulo',
  funcionalidade: '/funcionalidade',
  acessoModulo: '/acessoModulo',
  acessoFuncionalidade: '/acessoFuncionalidade',
  visitante: '/visitante',
  visita: '/visita',
  contribuicao: '/contribuicao', 
  veiculo: '/veiculo',
  apiUrl: 'localhost:9090/sgc',
  apiUrlCep: 'https://viacep.com.br/ws'
};
