---
version: '3'
services:

    zookeeper:
      image: confluentinc/cp-zookeeper:7.0.1
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      networks:
        - app-net
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  
    broker:
      image: confluentinc/cp-kafka:7.0.1
      hostname: broker
      container_name: broker
      depends_on:
        - zookeeper
      networks:
        - app-net
      ports:
        - "29092:29092"
        - "9092:9092"
        - "9101:9101"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_JMX_PORT: 9101
        SPRING_KAFKA_HOST: broker:29092
        
    kafdrop:
      image: obsidiandynamics/kafdrop:3.27.0
      networks:
        - app-net
      depends_on:
        - broker
      ports:
        - 9000:9000
      environment:
        KAFKA_BROKERCONNECT: broker:29092

    sgc:
      image: bpastorelli/associados
      restart: always
      build: 
        context: .
      ports:
        - "9090:8080"
      networks:
        - app-net
      depends_on:
        - broker
        - zookeeper
      environment:
        - SPRING_KAFKA_HOST=broker
        - TZ=America/Sao_Paulo
        - DEBIAN_FRONTEND=noninteractive
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
   
networks:
    app-net:  
