name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - develop
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        
    steps:
    # {2}
    - name: Checkout the source code
      uses: actions/checkout@v3

    # {3}
    - name: Setup Node.js $
      uses: actions/setup-node@v3
      with:
          node-version: $
          cache: 'npm'
          cache-dependency-path: package-lock.json

    # {4}
    - name: Install dependencies
    - working-directory: ./web
      run: npm ci
    # {5}
    - name: Run tests
    - working-directory: ./web
      run: npm run test:ci
    # {6}
    - name: Build
    - working-directory: ./web
      run: npm run build

    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application
      working-directory: .
      run: mvn clean package

    - name: Build Docker Compose Application
      working-directory: .
      run: docker compose build
      
    - name: Push Docker Compose Application
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/associados:latest ${{ secrets.DOCKER_USERNAME }}/associados:${{ github.run_id }} 
        
        docker push ${{ secrets.DOCKER_USERNAME }}/associados:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/associados:latest
        
