name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - develop
jobs:
 angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Node.js $
      uses: actions/setup-node@v3
      with:
        node-version: $
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      working-directory: ./web
      run: npm ci
      
    - name: Build
      working-directory: ./web
      run: npm run build

    - name: Build Docker Compose Application Angular
      working-directory: ./web
      run: docker compose build

    - name: Push Docker Compose Application Angular
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/sgc_angular:latest ${{ secrets.DOCKER_USERNAME }}/sgc_angular:${{ github.run_id }} 
        
        docker push ${{ secrets.DOCKER_USERNAME }}/sgc_angular:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/sgc_angular:latest
    
