name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - develop
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: ci
      working-directory: ./web   
      run: npm ci
    - name: build
      working-directory: ./web
      run: npm run build --if-present
    - name: test
      working-directory: ./web
      run: npm test
    
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application
      working-directory: .
      run: mvn clean package

    - name: Build Docker Compose Application
      working-directory: .
      run: docker compose build
      
    - name: Push Docker Compose Application
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/associados:latest ${{ secrets.DOCKER_USERNAME }}/associados:${{ github.run_id }} 
        
        docker push ${{ secrets.DOCKER_USERNAME }}/associados:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/associados:latest
        
